### PR TITLE
Changes to Support APO 2024

### PR DESCRIPTION
**Pull request by michaelmseymour**
Suppresses columns with the type of budget to improve readability of reports

### CODE REVIEW

**Comment by michaelmseymour** [comment]
I did the following things

- Created Signature Class/Signing functions to create contract for signature and create status
- I added files to support creation of the tables and alterations.
- I added .env options
- I created a test file to test my code. I couldn't my scripts to load the illuminate classes. But the code works in the test file and all debug things were brought over (although I might have left debug statements in there)

Cheers
Michael

**Review by itsrachelfish — CHANGES_REQUESTED** [review]
- Your PR includes the old budget question changes in addition to the document signing changes - https://github.com/playasoft/grants/pull/111
- You committed the vendor directory, which should be .gitignored 
- Lots of duplicated code for fetching data from the API using cURL, we should put all of this duplicated code into a helper function and potentially consider using `file_get_contents` instead of cURL

**Comment by michaelmseymour** [comment]
Also
- Adjust field to approved budget.
-

**Comment by itsrachelfish** [comment]
Closing this PR, please make another PR using your new branch - https://github.com/michaelmseymour/grants/tree/Repairs-for-Updates-for-2024

**Pull request closed without merging**
